name: ACM CUI
author: ACM International Conference on Conversational User Interfaces
title: ACM CUI
email: contact@cui.acm.org
lang: en-GB
locale: en-GB
tagline: >
  The ACM Conversational User Interfaces conference and workshop series
description: >-
  CUI, an Association for Computing Machinery Special Interest Group on Human Computer Interaction specialised conference, is the premier international venue for research on the design, development, and use of conversational interfaces. 

#baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:categories/:title/

# Social settings
social: 
  - https://www.linkedin.com/company/acm-cui/
  - https://threads.net/@acm_cui
  - https://hci.social/@cui
  - https://twitter.com/ACM_CUI
  - https://github.com/acm-cui
twitter:
  username: ACM_CUI
  card: summary
  creator: ACM_CUI

# Build settings
plugins_dir: ./_plugins
plugins:
  - jekyll-feed
  - jekyll-last-modified-at
  - jekyll-minifier
  - jekyll-optional-front-matter
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jekyll-menus

liquid:
  error_mode: strict
  strict_variables: false
  strict_filters: true

titles_from_headings:
  enabled: true
  strip_title: true
  collections: true

sass:
  style: compressed

jekyll-minifier:
  compress_css: false
  exclude: ['*.xml','*.csv']

# Sitemap configutation
defaults:
  - scope:
      path: ""
    values:
      image: /community/assets/icn/twitter.png
      layout: "textonly"
  - scope:
      path:            "assets/**/*.pdf"
    values:
      sitemap:         false

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
